const GEMINI_API_KEY = process.env.GEMINI_API_KEY ?? "";
const GEMINI_MODEL = "gemini-2.5-flash-image";
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`;

export async function generateAfterImage(
  base64Image: string,
  color?: string
): Promise<string> {
  const colorInstruction = color
    ? `Paint the exterior walls in a ${color} colour.`
    : "Use a clean, fresh, neutral colour for the walls.";

  const res = await fetch(GEMINI_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      contents: [
        {
          role: "user",
          parts: [
            {
              inlineData: {
                mimeType: "image/jpeg",
                data: base64Image,
              },
            },
            {
              text: `Generate an image of the SAME property but showing it after professional exterior treatment: wall coating, cleaning, and painting. ${colorInstruction} The property should look freshly treated with clean walls, no moss or algae, fresh even colour, repaired cracks, and clean gutters. Keep the same angle, same surroundings, same structure — only improve the exterior surfaces. Make it look realistic and professional.`,
            },
          ],
        },
      ],
      generationConfig: {
        responseModalities: ["TEXT", "IMAGE"],
      },
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    console.error("Gemini API error:", res.status, err);
    throw new Error(`Gemini API error: ${res.status}`);
  }

  const data = await res.json();
  const parts = data.candidates?.[0]?.content?.parts;

  if (!parts) {
    throw new Error("No response parts from Gemini");
  }

  const imagePart = parts.find(
    (p: { inlineData?: { data: string; mimeType: string } }) => p.inlineData
  );

  if (!imagePart?.inlineData) {
    throw new Error("No image generated by Gemini");
  }

  return `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`;
}
